

TARGET_CLASSES = {
  0: '<b>akiec, Actinic Keratoses or intraepithelial Carcinoma</b><p> - Actinic keratoses (AKs) are premalignant cutaneous lesions that may progress to squamous cell carcinoma. They are a common skin condition and develop in sun-exposed skin of individuals with cumulative sun exposure.</p><a href="#akiecs"><b> AKIEC</b> </a>',
  1: '<b>bcc, Basal Cell Carcinoma</b> <p>Basal cell carcinoma (BCC) is a common, locally invasive, keratinocyte cancer (also known as nonmelanoma cancer). It is the most common form of skin cancer. BCC is also known as rodent ulcer and basalioma. Patients with BCC often develop multiple primary tumours over time.</p><a href="#bccs"><b>Basal Cell Carcinoma</b> </a>',
  2: '<b>bkl, Benign Keratosis(Brown wart or Wisdom wart)</b><p> - Seborrhoeic keratosis is a harmless warty spot that appears during adult life as a common sign of skin ageing. Seborrhoeic keratosis is also called SK, basal cell papilloma, senile wart, brown wart, wisdom wart, or barnacle.  The descriptive term, benign keratosis, is a broader term that is used to include the following related scaly skin lesions: Seborrhoeic keratosis, Solar lentigo, and Lichen planus-like keratosis.</p><a href="#bkls"><b>Benign Keratosis</b></a>',
  3: '<b>df, Dermatofibroma</b> <p> - A dermatofibroma is a common benign fibrous nodule usually found on the skin of the lower legs. A dermatofibroma is also called a cutaneous fibrous histiocytoma.</p><a href="#dfs"><b>Dermatofibroma</b> </a>',
  4: '<b>mel, Melanoma</b><p>- Melanoma, also referred to as malignant melanoma, is a potentially very serious skin cancer in which there is an uncontrolled growth of melanocytes (pigment cells).</p><a href="#mels"><b>Melanoma</b></a>',
  5: '<b>nv, Melanocytic Nevi(Term Mole) </b><p> - A melanocytic naevus (American spelling ‘nevus’), or mole, is a common benign skin lesion due to a local proliferation of pigment cells (melanocytes). A brown or black melanocytic naevus contains the pigment melanin, so may also be called a pigmented naevus.</p><a href="#nvs"><b>Melanocytic Nevi (Term Mole)</b> </a>',
  6: '<b>vasc, Vascular skin lesion</b><p>- The terminology of vascular conditions can be confusing, with several lesions being incorrectly named or classified. Vascular skin lesions include: Vascular naevi, Angiomas, Telangiectases, Malignant vascular tumours.</p><a href="#vascs"><b>Vascular Skin Lesions</b></a>'

};
